# Generated by Django 3.2.3 on 2022-08-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='calc_price',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
