# Generated by Django 3.2.3 on 2022-08-31 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_price_calc_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='calc_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
